// export {default as Login} from './Login/Login'
export {default as LLogin} from './Login/LLogin'
export {default as Home} from './Home/Home'
// export {default as Register} from './Register/Register'
export {default as Register} from './Register/RRegister'
